name: 'Referenced action'
inputs:
  input1:  # id of input
    description: 'input1'
    required: false
    default: 'hehe'
outputs:
  output1:
    description: "Output"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo haha
      shell: bash
    - run: echo ${{ inputs.input1 }}.
      shell: bash
    - run: echo ${{ env.INPUT_input1 }}.
      shell: bash
    - run: echo ${{ github.actor }}.
      shell: bash
    - run: echo ${{ github.token }}.
      shell: bash
    - run: echo "$KEK_VAR".
      shell: bash
    - run: printenv
      shell: bash
    - id: random-number-generator
      run: echo "random-id=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
