name: 'Referenced action'
inputs:
  input1:  # id of input
    description: 'input1'
    required: false
    default: 'hehe'
runs:
  using: "composite"
  steps:
    - run: echo haha
      shell: bash
    - run: echo ${{ inputs.input1 }}.
      shell: bash
    - run: echo ${{ github.actor }}.
      shell: bash
    - run: echo ${{ github.token }}.
      shell: bash
    - run: echo "$KEK_VAR".
      shell: bash
